package com.kobe.quickcall.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTACT_BEAN".
*/
public class ContactBeanDao extends AbstractDao<ContactBean, Long> {

    public static final String TABLENAME = "CONTACT_BEAN";

    /**
     * Properties of entity ContactBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ContactId = new Property(1, String.class, "contactId", false, "CONTACT_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property PinName = new Property(3, String.class, "pinName", false, "PIN_NAME");
        public final static Property FirstPinName = new Property(4, String.class, "firstPinName", false, "FIRST_PIN_NAME");
        public final static Property Phone = new Property(5, String.class, "phone", false, "PHONE");
    }


    public ContactBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ContactBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTACT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CONTACT_ID\" TEXT," + // 1: contactId
                "\"NAME\" TEXT," + // 2: name
                "\"PIN_NAME\" TEXT," + // 3: pinName
                "\"FIRST_PIN_NAME\" TEXT," + // 4: firstPinName
                "\"PHONE\" TEXT);"); // 5: phone
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTACT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContactBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String contactId = entity.getContactId();
        if (contactId != null) {
            stmt.bindString(2, contactId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String pinName = entity.getPinName();
        if (pinName != null) {
            stmt.bindString(4, pinName);
        }
 
        String firstPinName = entity.getFirstPinName();
        if (firstPinName != null) {
            stmt.bindString(5, firstPinName);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(6, phone);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContactBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String contactId = entity.getContactId();
        if (contactId != null) {
            stmt.bindString(2, contactId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String pinName = entity.getPinName();
        if (pinName != null) {
            stmt.bindString(4, pinName);
        }
 
        String firstPinName = entity.getFirstPinName();
        if (firstPinName != null) {
            stmt.bindString(5, firstPinName);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(6, phone);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ContactBean readEntity(Cursor cursor, int offset) {
        ContactBean entity = new ContactBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // contactId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // pinName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // firstPinName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // phone
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContactBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContactId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPinName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFirstPinName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPhone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ContactBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ContactBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ContactBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
