package com.kobe.quickcall.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kobe.quickcall.greendao.ContactBean;

import com.kobe.quickcall.greendao.ContactBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactBeanDaoConfig;

    private final ContactBeanDao contactBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactBeanDaoConfig = daoConfigMap.get(ContactBeanDao.class).clone();
        contactBeanDaoConfig.initIdentityScope(type);

        contactBeanDao = new ContactBeanDao(contactBeanDaoConfig, this);

        registerDao(ContactBean.class, contactBeanDao);
    }
    
    public void clear() {
        contactBeanDaoConfig.clearIdentityScope();
    }

    public ContactBeanDao getContactBeanDao() {
        return contactBeanDao;
    }

}
